🎈 perf: optimize load_resource
anosora233/richi-console pull request #19
Opened 2024-04-09 13:27 UTC by lqgl

2024-04-11 04:46 UTC, anosora233 requested changes
有点小问题

2024-04-11 04:46 UTC, anosora233 commented on mhm/config.py
> +        ).build()
更新资源时会触发异常，因为重复访问了已被迭代消耗的响应内容。

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/user/repos/majsoul-hook-mitm/mhm/main.py", line 60, in <module>
    main()
  File "/home/user/repos/majsoul-hook-mitm/mhm/main.py", line 32, in main
    qbin_version, resger = load_resource()
                           ^^^^^^^^^^^^^^^
  File "/home/user/repos/majsoul-hook-mitm/mhm/config.py", line 104, in load_resource
    response.content, config.base.no_cheering_emotes
    ^^^^^^^^^^^^^^^^
  File "/home/user/repos/majsoul-hook-mitm/venv/lib/python3.11/site-packages/requests/models.py", line 894, in content
    raise RuntimeError("The content for this response was already consumed")
RuntimeError: The content for this response was already consumed

```

2024-04-11 04:47 UTC, lqgl commented
你好，你的邮件我已收到。

2024-04-11 04:58 UTC, lqgl commented on mhm/config.py
> +        ).build()
收到，晚点我尝试处理一下

2024-04-11 14:47 UTC, anosora233 commented on mhm/resource.py
> +        return ResourceManager(content, bin_version).build()
现在怎么样？

2024-04-11 14:47 UTC, anosora233 commented on mhm/config.py
移动 `load_resource()` 方法

2024-04-11 14:50 UTC, lqgl commented on mhm/resource.py
> +        return ResourceManager(content, bin_version).build()
还没来得及试，可能要晚点，加个discord交流下吗？https://discord.gg/GVXygY7S

2024-04-11 15:13 UTC, anosora233 commented on mhm/resource.py
> +        return ResourceManager(content, bin_version).build()
😲

2024-04-11 16:08 UTC, lqgl commented on mhm/resource.py
> +        return ResourceManager(content, bin_version).build()
我自己测了，没啥问题，你再试试看

2024-04-12 00:12 UTC, merged

2024-04-12 00:21 UTC, anosora233 approved these changes